version: '3.8'

services:
  grazindafranco:
    build: .
    restart: always
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: grazindafranco.com,www.grazindafranco.com
      LETSENCRYPT_HOST: grazindafranco.com,www.grazindafranco.com
      LETSENCRYPT_EMAIL: kyryl@bogach.es
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

